### ISSUE TITLE
你好，想问下，这个该怎么使用啊？

### ISSUE THREAD

**Issue by nealtsai888** [K265/frida-wechat-sticker#1]
想问下，是不是能把电脑里本地保存的，已经加密了个表情包解密出来呢？这个该如何使用能教一下吗，谢谢

**Comment by K265** [comment]
你好，已更新脚本和使用方法，请见 <https://github.com/K265/frida-wechat-sticker#usage>

**Comment by K265** [comment]
这个会在微信加载表情包的时候做一次解密，你可以运行脚本后，把表情包转发到文件传输助手。

**Comment by nealtsai888** [comment]
> 这个会在微信加载表情包的时候做一次解密，你可以运行脚本后，把表情包转发到文件传输助手。

你好，感谢大佬耐心解答，想问下，如果想批量解析，是不是就没辙了，相当于使用是单个单个表情包解析现在？

**Comment by K265** [comment]
我是先加到微信表情，然后在电脑打开的时候就会触发批量加载和解密了。

**Comment by nealtsai888** [comment]
> 

大概理解了，感谢大佬解答。不过我是发现电脑里有大量的加密的表情包，好奇到底都是些什么表情哈哈哈哈。
